"""Correctness fences for defects caused by the same logic living in many places.

Each of these shipped because a rule was reimplemented per-script and the copies
drifted. They are grouped here because they share one root cause, not because
they share a module.

  B10 heal_links and triage_links rewrote notes inside folders the user had
      excluded in .vault-config.json, which vault_health honours
  B26 freshness_lint read plain utf-8, so a BOM hid every freshness directive
  B27 vault_stats passed generated text as a regex replacement template
  B28 link_graph's inline-code span crossed newlines, erasing real links
  B29 the empty-folder check matched excludes against absolute path parts
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "scripts"))


def _run(script: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, f"scripts/{script}", *args],
        cwd=REPO_ROOT, capture_output=True, text=True,
        encoding="utf-8", errors="replace", check=False,
    )


def _note(p: Path, body: str, *, bom: bool = False) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8-sig" if bom else "utf-8")


# --- B10 -------------------------------------------------------------------

def test_heal_links_honours_vault_config_excludes(tmp_path):
    vault = tmp_path / "vault"
    _note(vault / "Archive" / "frozen.md", "---\ntype: note\n---\n\nsee [[Target Note]]\n")
    _note(vault / "target-note.md", "---\ntype: note\n---\n\nreal\n")
    (vault / ".vault-config.json").write_text(json.dumps({"exclude-paths": ["Archive"]}), encoding="utf-8")

    before = (vault / "Archive" / "frozen.md").read_text(encoding="utf-8")
    result = _run("heal_links.py", "--path", str(vault), "--batch")

    assert result.returncode == 0, result.stderr
    assert (vault / "Archive" / "frozen.md").read_text(encoding="utf-8") == before, (
        "heal_links rewrote a note inside an excluded folder; the read-only health "
        "check would not have reported it, so the two disagree"
    )


# --- B26 -------------------------------------------------------------------

def test_freshness_lint_reads_frontmatter_through_a_bom(tmp_path):
    """The body must contain a claim that actually trips FRESH-1.

    A first version used a claim that already carried an "as of" stamp, so
    nothing fired either way and the test passed with the fix reverted. The
    exemption can only be shown to work if there is something to exempt.
    """
    vault = tmp_path / "vault"
    # A bare volatile quantitative claim with no stamp: this trips FRESH-1.
    body = "---\ntype: note\nfreshness: snapshot\n---\n\nThe team has 12 engineers and revenue is $50,000.\n"
    _note(vault / "bom.md", body, bom=True)

    result = _run("freshness_lint.py", "--path", str(vault), "--json")
    payload = json.loads(result.stdout[result.stdout.index("{"):])

    assert payload["errors"] == 0, (
        "the BOM'd note was linted despite `freshness: snapshot`. The BOM survived "
        f"into the first line, so the frontmatter fence was never matched: {payload['findings']}"
    )


def test_freshness_lint_still_flags_an_unexempted_claim(tmp_path):
    """Guards the test above: prove the fixture really is lintable."""
    vault = tmp_path / "vault"
    _note(vault / "nostamp.md", "---\ntype: note\n---\n\nThe team has 12 engineers and revenue is $50,000.\n")
    result = _run("freshness_lint.py", "--path", str(vault), "--json")
    payload = json.loads(result.stdout[result.stdout.index("{"):])
    assert payload["errors"] == 1, "the fixture no longer trips FRESH-1, so the BOM test proves nothing"


# --- B27 -------------------------------------------------------------------

def test_vault_stats_survives_a_backslash_in_frontmatter(tmp_path):
    """index.md must already carry the stats markers.

    Without them update_index takes the plain-append branch and never reaches
    the regex substitution, so a first version of this test passed with the fix
    reverted. The markers are what force the re.sub path.
    """
    vault = tmp_path / "vault"
    _note(vault / "Projects" / "p.md", '---\ntype: project\nstatus: "on hold \\perf"\n---\n\nbody\n')
    _note(
        vault / "index.md",
        "---\ntype: index\n---\n\n# Index\n\n"
        "<!-- BEGIN STATS - generated by vault_stats.py -->\nold\n<!-- END STATS -->\n",
    )

    result = _run("vault_stats.py", "--path", str(vault))
    assert result.returncode == 0, (
        "a backslash in a frontmatter value aborted the run - the generated block "
        f"was being used as a regex replacement template:\n{result.stderr}"
    )
    assert "bad escape" not in result.stderr


# --- B28 -------------------------------------------------------------------

def test_link_graph_stray_backtick_does_not_erase_links(tmp_path):
    import link_graph
    import vault_health

    text = "Don`t use the old flow.\n\nSee [[target]] for details.\n\nUse the `x` flag.\n"
    assert "[[target]]" in link_graph._strip_code(text), (
        "a stray backtick swallowed the paragraph containing a real link"
    )
    assert "[[target]]" in vault_health._strip_code(text)
    # And the two modules must agree, which is what link_graph's docstring promises.
    assert link_graph.INLINE_CODE_RE.pattern == vault_health.INLINE_CODE_RE.pattern


# --- B29 -------------------------------------------------------------------

def test_empty_folder_check_is_not_disabled_by_an_ancestor_directory_name(tmp_path):
    import vault_health

    # The vault itself sits under a directory named "Templates", which is in the
    # default exclude set. Only the path *inside* the vault should be considered.
    vault = tmp_path / "Templates" / "myvault"
    _note(vault / "note.md", "---\ntype: note\n---\n\nbody\n")
    (vault / "EmptyDir").mkdir(parents=True)

    findings = vault_health.check_empty_folders(vault, vault_health.load_vault_config(vault))
    assert any("EmptyDir" in str(f) for f in findings), (
        "the empty-folder check reported nothing because an ancestor directory "
        "outside the vault shared a name with an excluded directory"
    )


# --- B30 -------------------------------------------------------------------

def test_template_leftover_ignores_template_syntax_quoted_in_code(tmp_path):
    import vault_health

    # A dev log that *writes about* a templating engine quotes its syntax in a
    # code span or fence. Every other scanner in this file treats code as
    # quotation (_strip_code); the template check read the raw body, so notes
    # discussing Eta/EJS templates were reported as unfilled templates forever.
    quoted = (
        "---\ntype: devlog\n---\n\n"
        "The layout interpolates with `<%= it.name %>` per field:\n\n"
        "```eta\n<%= it.order.id %>\n```\n"
    )
    real = "---\ntype: note\n---\n\nHello <%= name %>, welcome aboard.\n"

    flagged = {
        i["files"][0]
        for i in vault_health.check_template_leftovers({
            "log/quoted.md": {"content": quoted},
            "log/real.md": {"content": real},
        })
    }
    assert "log/quoted.md" not in flagged, (
        "template syntax quoted inside code was reported as an unfilled template"
    )
    assert "log/real.md" in flagged, (
        "a genuinely unfilled placeholder in prose must still be reported"
    )
