#!/usr/bin/env python3
"""Compute deterministic vault stats and rewrite the marked block in index.md.

Walks the vault, parses YAML frontmatter from every .md file, aggregates by
`type` and `status`, then replaces the content between
    <!-- BEGIN STATS - generated by vault_stats.py -->
    <!-- END STATS -->
markers in <vault>/index.md. Idempotent - only the marked block is touched.

Usage:
    python scripts/vault_stats.py --path /path/to/vault [--print-only] [--json]
    (--vault is accepted as an alias for --path)

--print-only  emit the new stats block to stdout without writing
--json        emit the raw aggregates as JSON (for tooling / Bases sidecar)
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter
from datetime import date, datetime
from pathlib import Path
from typing import Any

FRONTMATTER = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)

# Folders we don't want in the count (templates, references, attachments, etc.).
# .git and _export matter most: the OKF export writes a full markdown copy of the
# vault under _export/, so counting it doubles every stat after an export.
# All values are lowercase - comparison uses part.lower() so casing in the vault doesn't matter.
import sys as _sys
from pathlib import Path as _Path

_sys.path.insert(0, str(_Path(__file__).resolve().parent))
from vault_scan import BASE_EXCLUDE_DIRS, STATS_ONLY_EXCLUDES  # noqa: E402

# Base policy plus raw/ and references/, which are real vault content but not
# user notes for the purpose of counting.
# cs-adaptace: log/ joins them - the Czech vault's append-only op-log tree is
# machine output, and counting it inflates every note statistic. (sablony/ comes
# in through the base, next to upstream's "templates".)
EXCLUDED_FOLDERS = frozenset(
    d.lower() for d in (*BASE_EXCLUDE_DIRS, *STATS_ONLY_EXCLUDES, "log")
)

STATS_BEGIN = "<!-- BEGIN STATS - generated by vault_stats.py -->"
STATS_END = "<!-- END STATS -->"


def parse_frontmatter(text: str) -> dict[str, Any]:
    """Lightweight YAML frontmatter parser. No dependency on PyYAML.

    Handles only the subset we need: scalar `key: value` lines. Lists and
    nested objects are stored as raw strings; we don't aggregate on them.
    """
    m = FRONTMATTER.match(text)
    if not m:
        return {}
    fm: dict[str, Any] = {}
    for line in m.group(1).splitlines():
        line = line.rstrip()
        # Continuation lines start with ANY whitespace - a tab-indented nested key
        # (meta: / status:) must never be read as a top-level field, or a nested
        # `type:` silently overwrites the note's real type.
        if not line or line[0] in " \t" or line.startswith("#") or line.startswith("-"):
            continue
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        val = val.strip().strip('"').strip("'")
        fm[key.strip()] = val if val else None
    return fm


def walk_vault(vault: Path) -> tuple[list[tuple[Path, dict[str, Any]]], int]:
    """Return (notes, skipped_unreadable).

    A count is only as honest as its denominator: files we cannot read are
    skipped, but each one is named on stderr and the total is reported in the
    stats, so an undercount is never presented as fact."""
    out: list[tuple[Path, dict[str, Any]]] = []
    skipped = 0
    for md in vault.rglob("*.md"):
        rel_parts = md.relative_to(vault).parts
        if any(part.lower() in EXCLUDED_FOLDERS for part in rel_parts):
            continue
        if md.name in {"_CLAUDE.md", "log.md", "index.md", "MEMORY.md"}:
            continue
        try:
            text = md.read_text(encoding="utf-8-sig")
        except (UnicodeDecodeError, OSError):
            rel = "/".join(rel_parts)
            sys.stderr.write(f"warning: skipped unreadable note (not UTF-8): {rel}\n")
            skipped += 1
            continue
        fm = parse_frontmatter(text)
        out.append((md, fm))
    return out, skipped


def parse_iso_date(value: Any) -> date | None:
    if not value or not isinstance(value, str):
        return None
    try:
        return datetime.strptime(value[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


def compute(notes: list[tuple[Path, dict[str, Any]]], skipped_unreadable: int = 0) -> dict[str, Any]:
    by_type: Counter[str] = Counter()
    project_status: Counter[str] = Counter()
    person_strength: Counter[str] = Counter()
    idea_status: Counter[str] = Counter()
    task_status: Counter[str] = Counter()
    research_subtype: Counter[str] = Counter()

    latest_per_folder: dict[str, date] = {}
    interaction_dates: list[date] = []

    today = date.today()

    for path, fm in notes:
        ntype = fm.get("type") or "untyped"
        by_type[ntype] += 1

        if ntype == "project":
            project_status[fm.get("status") or "unknown"] += 1
        elif ntype in {"person", "entity"}:
            # count both: ai-first-rules.md uses `type: person`, some vaults use `type: entity`
            person_strength[fm.get("strength") or "unknown"] += 1
            d = parse_iso_date(fm.get("last-interaction"))
            if d:
                interaction_dates.append(d)
        elif ntype == "idea":
            idea_status[fm.get("status") or "unknown"] += 1
        elif ntype == "task":
            task_status[fm.get("status") or "unknown"] += 1
        elif ntype == "research":
            research_subtype[fm.get("subtype") or "unknown"] += 1

        folder = path.parent.name
        d = parse_iso_date(fm.get("date") or fm.get("updated") or fm.get("created"))
        if d and (folder not in latest_per_folder or d > latest_per_folder[folder]):
            latest_per_folder[folder] = d

    total_notes = sum(by_type.values())

    return {
        "generated_at": today.isoformat(),
        "total_notes": total_notes,
        "skipped_unreadable": skipped_unreadable,
        "by_type": dict(by_type),
        "projects": {
            "total": by_type.get("project", 0),
            "by_status": dict(project_status),
        },
        "people": {
            "total": by_type.get("person", 0) + by_type.get("entity", 0),
            "by_strength": dict(person_strength),
            "most_recent_interaction": max(interaction_dates).isoformat() if interaction_dates else None,
        },
        "ideas": {
            "total": by_type.get("idea", 0),
            "by_status": dict(idea_status),
        },
        "tasks": {
            "total": by_type.get("task", 0),
            "by_status": dict(task_status),
        },
        "research": {
            "total": by_type.get("research", 0),
            "by_subtype": dict(research_subtype),
        },
        "knowledge": {"total": by_type.get("decision-record", 0) + by_type.get("knowledge", 0)},
        "logs": {"total": by_type.get("log", 0)},
        "dev_logs": {"total": by_type.get("dev-log", 0)},
        "latest_per_folder": {k: v.isoformat() for k, v in sorted(latest_per_folder.items())},
    }


def render_block(stats: dict[str, Any]) -> str:
    """Render the human-readable stats block (between BEGIN/END markers)."""

    def fmt_counter(d: dict[str, int]) -> str:
        if not d:
            return "-"
        return ", ".join(f"{n} {k}" for k, n in sorted(d.items(), key=lambda x: -x[1]))

    p = stats["projects"]
    pe = stats["people"]
    i = stats["ideas"]
    t = stats["tasks"]
    r = stats["research"]

    lines = [
        STATS_BEGIN,
        f"_Generated by `scripts/vault_stats.py` on {stats['generated_at']}._",
        "",
        f"- **Total notes**: {stats['total_notes']}"
        + (f" ({stats['skipped_unreadable']} unreadable file(s) skipped)"
           if stats.get("skipped_unreadable") else ""),
        f"- **Projects**: {p['total']} ({fmt_counter(p['by_status'])})",
        f"- **People**: {pe['total']} ({fmt_counter(pe['by_strength'])})"
        + (f" - last interaction {pe['most_recent_interaction']}" if pe["most_recent_interaction"] else ""),
        f"- **Ideas**: {i['total']} ({fmt_counter(i['by_status'])})",
        f"- **Tasks**: {t['total']} ({fmt_counter(t['by_status'])})",
        f"- **Research**: {r['total']} ({fmt_counter(r['by_subtype'])})",
        f"- **Knowledge**: {stats['knowledge']['total']}",
        f"- **Dev Logs**: {stats['dev_logs']['total']}",
        f"- **Operation logs**: {stats['logs']['total']} day(s)",
        "",
        f"_Latest activity per folder: {', '.join(f'{k} ({v})' for k, v in stats['latest_per_folder'].items())}_",
        STATS_END,
    ]
    return "\n".join(lines)


def update_index(vault: Path, block: str) -> bool:
    index = vault / "index.md"
    if not index.is_file():
        sys.stderr.write(f"warning: {index} not found - printing block to stdout instead\n")
        print(block)
        return False
    text = index.read_text(encoding="utf-8-sig")
    pattern = re.compile(
        re.escape(STATS_BEGIN) + r".*?" + re.escape(STATS_END),
        re.DOTALL,
    )
    if pattern.search(text):
        # A lambda, not a string: as a string, re.sub interprets backslash
        # escapes, so a frontmatter value containing \p aborts the run with
        # `bad escape` and one containing \1 silently injects a group.
        new_text = pattern.sub(lambda _m: block, text)
    else:
        # Append block if markers are absent (first run on a vault that doesn't yet have them)
        new_text = text.rstrip() + "\n\n" + block + "\n"
    if new_text != text:
        index.write_text(new_text, encoding="utf-8")
        return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    # --path matches every sibling script (vault_health, heal_links, link_graph,
    # export_okf, ...); --vault stays as the historical alias.
    ap.add_argument("--path", "--vault", dest="vault", required=False, type=Path,
                    default=os.environ.get("OBSIDIAN_VAULT_PATH") or os.environ.get("OBSIDIAN_VAULT"),
                    help="Path to vault root (default: $OBSIDIAN_VAULT_PATH, "
                         "falling back to the legacy $OBSIDIAN_VAULT)")
    ap.add_argument("--print-only", action="store_true", help="Print block to stdout, do not modify index.md")
    ap.add_argument("--json", action="store_true", help="Emit raw aggregates as JSON (machine-readable)")
    args = ap.parse_args()

    if not args.vault:
        ap.error("--path is required or set OBSIDIAN_VAULT_PATH env var")

    vault = Path(args.vault).resolve()
    notes, skipped = walk_vault(vault)
    stats = compute(notes, skipped)

    if args.json:
        json.dump(stats, sys.stdout, indent=2)
        sys.stdout.write("\n")
        return 0

    block = render_block(stats)

    if args.print_only:
        print(block)
        return 0

    changed = update_index(vault, block)
    print(f"{'Updated' if changed else 'No change to'} {vault / 'index.md'} - {stats['total_notes']} notes processed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
