#!/usr/bin/env bash
# =============================================================================
# adapters/codex-cli/adapter.sh - OpenAI Codex CLI platform adapter
# =============================================================================
# Codex CLI ships native Agent Skills (since Dec 2025): a skill is a directory
# under `.agents/skills/<name>/` with a `SKILL.md` (name + description
# frontmatter + instructions). Codex loads only each skill's name/description
# until it selects one (progressive disclosure), then runs it IN-SESSION - the
# agent invokes it with `$<name>`, `/skills`, or implicitly by description.
#
# We therefore emit one native skill per command. AGENTS.md stays as a thin
# always-on operating manual (AI-first rule + how skills work); it no longer
# carries a giant routing table, because Codex discovers skills itself.
#
# This replaces the previous AGENTS.md-routing-table + `codex exec` wrapper
# design, which had no session continuity, no native skill discovery, ambiguous
# write permissions, and per-command startup overhead.
# =============================================================================

CODEX_PLATFORM="codex-cli"
CODEX_DIR="codex"
CODEX_SKILLS_DIR=".agents/skills"
CODEX_DISPATCHER="AGENTS.md"

adapter_build() {
  local src="$1" dst="$2"

  _codex_emit_dispatcher "$src" "$dst"
  _codex_emit_skills "$src/commands" "$dst/$CODEX_SKILLS_DIR"
  _codex_copy_references "$src/references" "$dst/.${CODEX_DIR}/references"
  _codex_copy_scripts "$src/scripts" "$dst/.${CODEX_DIR}/scripts"
  _codex_emit_install_hint "$dst"
}

# Emit AGENTS.md at the dist root. Thin always-on manual - no routing table,
# because Codex's native skill discovery (progressive disclosure) handles
# routing. We just tell the agent the skills exist and the AI-first rule.
_codex_emit_dispatcher() {
  local src="$1" dst="$2"
  local out="$dst/$CODEX_DISPATCHER"
  local count=0 f
  for f in "$src"/commands/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$CODEX_PLATFORM" && count=$((count + 1))
  done

  {
    cat <<EOF
# Obsidian Second Brain - Codex CLI Operating Manual

This vault runs the **obsidian-second-brain** skill as ${count} native Codex
**Agent Skills** under \`.agents/skills/\`. Codex discovers them automatically:
each skill's name and description are always visible, and the full instructions
load only when a skill is selected (progressive disclosure).

## How to operate

1. Read \`_CLAUDE.md\` in the vault root, if it exists, to learn the user's
   vault conventions (folder map, daily note format, naming).
2. When the user's request matches a skill, invoke it - by \`\$<skill-name>\`,
   via \`/skills\`, or let Codex select it implicitly from its description.
   You do not need a routing table here; the skill list is the router.
EOF

    emit_ai_first_rule ".codex/references/ai-first-rules.md"

    cat <<EOF
4. Do not invent skills. If none matches, ask the user or fall back to plain
   natural-language help.

## Scripts

Python helpers live under \`.codex/scripts/\`. They run via
\`(cd .codex && uv run -m scripts.research.<name> ...)\` - \`.codex/\` is a
self-contained uv project, so modules and dependencies both resolve. Skills that need them
reference the exact invocation inside the skill body.

---

*Generated by adapters/codex-cli/adapter.sh - do not edit manually.*
EOF
  } > "$out"
}

# Emit one native Codex skill per command:
#   .agents/skills/<name>/SKILL.md
# Frontmatter carries `name` + `description` (required by Codex). We fold the
# command's English triggers into the description so Codex's implicit selection
# matches them. The body is the command body, tool-neutralized and
# path-rewritten so references/scripts resolve under .codex/.
_codex_emit_skills() {
  local src="$1" dst="$2"
  [[ -d "$src" ]] || return 0
  local f name desc triggers out
  for f in "$src"/*.md; do
    [[ -f "$f" ]] || continue
    should_include "$f" "$CODEX_PLATFORM" || continue

    name="$(basename "$f" .md)"
    desc="$(parse_frontmatter "$f" description)"
    triggers="$(parse_frontmatter "$f" triggers_en)"
    local trigmode
    trigmode="$(parse_frontmatter "$f" trigger-mode)"
    [[ -z "$desc" ]] && desc="Run the $name command of the obsidian-second-brain skill."

    # Fold triggers into the description for implicit selection.
    if [[ -n "$triggers" ]]; then
      local trig_clean
      trig_clean="$(format_triggers "$triggers")"
      [[ -n "$trig_clean" ]] && desc="$desc Triggers: $trig_clean."
    fi

    # This build writes its own frontmatter, so a source trigger-mode does not
    # travel unless it is encoded here (#181).
    desc="$(with_trigger_policy "$desc" "$trigmode")"

    mkdir -p "$dst/$name"
    out="$dst/$name/SKILL.md"
    {
      echo "---"
      echo "name: $name"
      # Quote the description; escape embedded double quotes.
      printf 'description: "%s"\n' "${desc//\"/\\\"}"
      echo "---"
      echo
      command_body "$f"
    } > "$out"

    rewrite_tool_neutral "$out"
    rewrite_skill_root "$out" ".${CODEX_DIR}"
    rewrite_platform_paths "$out" "$CODEX_DIR"
  done
}

_codex_copy_references() { copy_references_rewritten "$1" "$2" "$CODEX_DIR"; }  # see adapters/lib.sh

_codex_copy_scripts() { copy_scripts_with_project "$1" "$2"; }  # see adapters/lib.sh

_codex_emit_install_hint() {
  local dst="$1"
  cat > "$dst/INSTALL.md" <<'EOF'
# Install on Codex CLI

> **Deprecated.** This per-platform build is superseded by the unified Agent
> Skills build (`bash scripts/build.sh --platform agent-skills`), which emits
> one spec-compliant `.agents/skills/` tree that Codex CLI, OpenCode, and
> Google Antigravity all read, and installs via `npx skills`. This codex-cli
> build still works but will be removed in a future release. See
> `dist/agent-skills/INSTALL.md`.

```bash
# From the repo root, after running `bash scripts/build.sh --platform codex-cli`:
# Copy (or symlink) the built tree into your vault root:
cp -R dist/codex-cli/. /path/to/your/vault/
```

Then in your vault:

- `.agents/skills/<name>/SKILL.md` are native Codex Agent Skills. Codex
  discovers them automatically and loads each one's instructions only when it
  is selected (progressive disclosure). Invoke a skill with `$<name>`, pick it
  from `/skills`, or just describe the task and let Codex match it.
- `AGENTS.md` is the always-on operating manual Codex reads at session start
  (vault conventions + the AI-first rule). It is intentionally thin - the skill
  list is the router.
- `.codex/references/` holds shared specs (the AI-first vault rule) that skills
  reference.
- `.codex/scripts/` holds the Python helpers invoked by the research toolkit
  skills, plus a `pyproject.toml` making `.codex/` a self-contained uv project.
  Run them via `(cd .codex && uv run -m scripts.research.<name> ...)`.

## Where you start Codex is load-bearing

Start Codex CLI **from the vault root**, or have the vault under git. This is a
requirement, not a convenience:

- Codex walks up to the **git root** looking for `.agents/skills`. A git-backed
  vault therefore works from any subfolder - all skills still register.
- A plain Obsidian vault is not a git repo. In that case, opening Codex in any
  subfolder registers **zero** skills. There is no warning and no error;
  `/skills` is simply empty and the session behaves like stock Codex.
- The `.codex/references/` paths the skills cite are relative to this root too.
  Start elsewhere and the AI-first spec is a dead path.

If you keep your vault outside git and want to work from subfolders, run
`git init` in the vault root once. Reported by @Palo-Alto-AI-Research-Lab on
codex-cli 0.144.4 (issue #171).

## Write-time validation hook (not included)

This build ships no `hooks/` directory. The write-time AI-first validator
(`validate-ai-first.sh`) is wired only in the Claude Code build. If your host
exposes a post-write hook, wire it yourself from the source repo:
`hooks/validate-ai-first.hook.yaml` is the platform-neutral spec and
`hooks/validate-ai-first.sh` the implementation. Without it, the AI-first rule
is enforced by the skill instructions alone.

Skills run in your current session - no `codex exec` wrapper, no per-command
startup, and writes honor your session's approval/sandbox mode.
EOF
}
